### ISSUE TITLE
Unlockable commands

### ISSUE THREAD

**Issue by MaxWasUnavailable** [LethalCompany/LethalAPI.TerminalCommands#10]
Thoughts on a system for unlockable commands?

E.g. a command can only be run once it's "unlocked". How stuff is unlocked can be sorted out elsewhere (e.g. buying the command, finding a "disc", etc...)

Technically, you can already do this by adding a conditional in the command definition, but I wonder if it's interesting / useful to add this as an attribute?

**Comment by ShimmyMySherbet** [comment]
This can already be implemented by inheriting the `AccessControlAttribute`, and annotating commands with it.

An example of this in one of my own mods, is making a `teleport` command only available when the teleporter is unlocked.

When any `AccessControlAttribute`s return `false`, the command is not executed, and does not show up in any help messages. In effect, the command doesn't exist until the all `AccessControlAttribute`s return `true`.
