### ISSUE TITLE
Release DLL [Not A Issue]

### ISSUE THREAD

**Issue by AvocadoVR** [LethalCompany/LethalAPI.TerminalCommands#15]
Could you publish the latest DLL including the Terminal Interactions.

**Comment by ShimmyMySherbet** [comment]
Terminal interactions have been completed and merged into development.
I still need to do a review over the entire library, but then it should be set for the first major release, and release on Thunderstore.

**Comment by ShimmyMySherbet** [comment]
The mod as been fully released now, and you can find it on Thunderstore: https://thunderstore.io/c/lethal-company/p/LethalAPI/LethalAPI_Terminal/
