### ISSUE TITLE
Change repo name to LethalAPI.LibTerminal as the project rebranded

### ISSUE THREAD

**Issue by ustaalon** [LethalCompany/LethalAPI.TerminalCommands#19]
Change the repo name to LethalAPI.LibTerminal as the project rebranded

**Comment by ShimmyMySherbet** [comment]
I've already asked @MaxWasUnavailable to rename the library, so just waiting on him. Though this is non-urgent, and everyone is likely tied up in new year's celebration.

Though the library is being renamed to `LethalAPI.Terminal`, not `LibTerminal`. `LethalAPI.LibTerminal` is only used in the source code to prevent reference ambiguity between the `Terminal` type, and the `.Terminal` namespace.

Also, this issue would fall under #13, as it is the next step in rebranding the library
