### ISSUE TITLE
QA Status for V1 final changes (BDD)

### ISSUE THREAD

**Issue by ustaalon** [LethalCompany/LethalAPI.TerminalCommands#24]
### VERIFIED ###

**Given** a player installed LethalAPI.Terminal
**When** a player enters Lethal Company Modded
**And** LethalAPI.Terminal is installed
**Then** LethalAPI.Terminal initiate logger message should be displayed in the BepInEx console
**VALID**

**Given** a player enters the ship's terminal
**When** a player enters Lethal Company Modded
**And** LethalAPI.Terminal is installed
**Then** ship's terminal should work correctly
**VALID**

**Given** a player enters the `Other` menu in the ship's terminal
**When** the player enters the ship's terminal
**And** the player goes to `Other` menu
**Then** the player will see all registered commands
**VALID**

**Given** a player goes to terminal interaction of type `TerminalInteraction`
**When** the player enters the ship's terminal
**And** the player goes to `Other` menu
**And** the player goes to command interaction of type `TerminalInteraction` with `InteractionCallback`
**And** the player should see `TerminalInteraction` interface in the terminal
**And** the player hits enter
**Then** `InteractionCallback` should be invoked
**VALID**

**Given** a player goes to terminal interaction of type `ConfirmInteraction` and `Confirm`
**When** the player enters the ship's terminal
And the player goes to `Other` menu
And the player goes to command interaction of type `ConfirmInteraction` with `DenyCallback` delegate for deny and `ConfirmCallback` delegate for confirm
**And** the player should see `ConfirmInteraction` interface in the terminal
**And** the player `Confirm`
**Then** `ConfirmCallback` should be invoked
**VALID**

**Given** a player goes to terminal interaction of type `ConfirmInteraction` and `Deny`
**When** the player enters the ship's terminal
**And** the player goes to `Other` menu
**And** the player goes to command interaction of type `ConfirmInteraction` with `DenyCallback` delegate for deny and `ConfirmCallback` delegate for confirm
**And** the player should see `ConfirmInteraction` interface in the terminal
**And** the player `Deny`
**Then** `DenyCallback` should be invoked
**VALID**

**Given** a developer wrote a new command and registered it 
**When** the player enters the ship's terminal
**And** the player goes to `Other` menu
**Then** the player will see the registered commands
**VALID**

**Given** a developer wrote a new command and did not register it 
**When** the player enters the ship's terminal
**And** the player goes to `Other` menu
**Then** the player will not see the unregistered command
**VALID**

**Given** a developer wrote a new command and used `AllowedCaller(AllowedCaller.None)` Attribute
**When** the player enters the ship's terminal
**And** the player goes to `Other` menu
**Then** none of the players will be able to use and see this command
**VALID**

**Given** a developer wrote a new command and used `AllowedCaller(AllowedCaller.Player)` Attribute
**When** the player enters the ship's terminal
**And** the player goes to `Other` menu
**Then** all of the players will be able to use and see this command
**VALID**

**Given** a developer wrote a new command and used `AllowedCaller(AllowedCaller.Host)` Attribute
**When** the player enters the ship's terminal
**And** the player goes to `Other` menu
**Then** only the host will be able to use and see this command
**VALID**

**Given** a developer wrote a new command `confirm` and used `RequireInterface(typeof(ConfirmInteraction))` Attribute
**When** the player enters the ship's terminal
**And** the player goes to `Other` menu
**And** the player goes to command interaction of type `ConfirmInteraction` with `DenyCallback` delegate for deny and `ConfirmCallback` delegate for confirm
**And** the player should see `ConfirmInteraction` interface in the terminal
**And** the player `Confirm`
**Then** `ConfirmCallback` should be invoked
And `ConfirmCallback` ran after `ConfirmInteraction` interface
**VALID**

**Given** a developer wrote a new command `deny` and used `RequireInterface(typeof(ConfirmInteraction))` Attribute
**When** the player enters the ship's terminal
**And** the player goes to `Other` menu
**And** the player goes to command interaction of type `ConfirmInteraction` with `DenyCallback` delegate for deny and `ConfirmCallback` delegate for confirm
**And** the player should see `ConfirmInteraction` interface in the terminal
**And** the player `Confirm`
**Then** `DenyCallback` should be invoked
And `DenyCallback` ran after `ConfirmInteraction` interface
**VALID**

**Given** a developer wrote a new command `Store` and used `CommandPriority` Attribute
**When** the player enters the ship's terminal
**And** the player goes to `Store` command
**Then** the player will see the custom `Store` command
**VALID**

**Given** a developer wrote a new command `Tools` and used `TerminalCommand` Attribute with `clearText: true`
**When** the player enters the ship's terminal
**And** the player goes to `Tools` command
**Then** the player will see the custom `Tools` command
**And** previous text in the terminal will be cleared
**VALID**

**Given** a developer wrote a new command `Tools` and used `TerminalCommand` Attribute with `clearText: false`
**When** the player enters the ship's terminal
**And** the player goes to `Tools` command
**Then** the player will see the custom `Tools` command
**And** previous text in the terminal will not be cleared
**VALID**

**Given** a developer wrote a new command `Video` that plays a video link (using: `PlayVideoLink`)
**When** the player enters the ship's terminal
**And** the player goes to `Video` command
**Then** the player will see the video link
**VALID**

**Given** a developer wrote a new command `Video` that plays a video file (using: `PlayVideoFile`)
**When** the player enters the ship's terminal
**And** the player goes to `Video` command
**Then** the player will see the video file
**VALID**

**Given** multiple mods using LethalAPI.Terminal library
**When** the player enters the ship's terminal
**And** the player goes to `Other` menu
**Then** the player will see the registered commands
**VALID**

**Please let me know if I missed important users flows using the library**

**Comment by ShimmyMySherbet** [comment]
could you elaborate on this one? Not sure what this one means
> Given a player goes to terminal interaction of type TerminalInteraction
When the player enters the ship's terminal
And the player goes to Other menu
And the player goes to command interaction of type TerminalInteraction with InteractionCallback
And the player should see TerminalInteraction interface in the terminal
And the player hits enter
Then InteractionCallback should be invoked
NEED CLARIFICATION OF USER FLOW

**Comment by ustaalon** [comment]
I'm not sure for 100% percent what should be the user flow when using this interaction, I did this flow:

1. New command called `test` (listed as 'test' in 'other' menu)
2. Command `test` will return TerminalInteraction with values of TerminalNode and and Handler
3. DisplayText of the interaction will be displayed and when entering something in the terminal again and submit, the handler will be invoked

```cs
        [TerminalCommand("test", clearText: true), CommandInfo("checking commands")]
        public ITerminalInteraction RabbiCommand()
        {
            var builder = new StringBuilder();
            builder.AppendLine("test display text");

            var terminalNode = new TerminalNode()
            {
                displayText = builder.ToString()
            };

            return new TerminalInteraction(terminalNode, InteractionHandler);
        }
```

I want to make sure, is this the right flow?

**Comment by ShimmyMySherbet** [comment]
I think you have the gist of it?
There, the command will have the response of 'test display text', and then the next input into the terminal will be handled by the interaction handler, so long as the terminal input is compatible with it's signature.
So what happens when the user enters something into the terminal again depends on `InteractionHandler`, of which you have not listed the code for.

**Comment by ShimmyMySherbet** [comment]
The use of the `TerminalInteraction` type is meant to be a common type that allows a command to prompt for more info.
E.g.,
![image](https://github.com/LethalCompany/LethalAPI.Terminal/assets/44135337/28a6e01b-fa83-42ca-8463-e92fe1e754df)

**Comment by ustaalon** [comment]
Alright. That great.
I will make sure to validate it again today.

Any more validations you want me to add to the next release?

**Comment by ustaalon** [comment]
@ShimmyMySherbet 
All the above scenarios are valid.

Please let me know if there are other important scenarios that I should test.
