### ISSUE TITLE
Chat support for Terminal Commands

### ISSUE THREAD

**Issue by ShimmyMySherbet** [LethalCompany/LethalAPI.TerminalCommands#5]
* Add an attribute to mark a terminal command as accessible in chat
  * Therefore chat commands can just funnel into the same command processing system as terminal commands
* Disabled by default, can enable it via config or extra CLI argument to the game
* Probably include `other` in the chat commands, but have it exclude all non-chat accessible commands
* Add a `CommandContext` object to the terminal commands injection context, which can include info such as
  * If the command was executed in chat or terminal
  * Sending terminal, or null
  * Calling PlayerCharacterB (useful for chat commands)
* (Maybe) allow a command to be executed client-side or server side
  * (Permission restrictions still apply either way)

**Comment by ShimmyMySherbet** [comment]
Suggested by @Redforce04

**Comment by Redforce04** [comment]
I'll take a look at this tomorrow

**Comment by ShimmyMySherbet** [comment]
I can handle the implementation, will be pretty easy.
Just opened this for discussion and reference

**Comment by MaxWasUnavailable** [comment]
I think it would be nice to support chat commands through the API, but I feel like the Terminal is a part of gameplay (at the ship, slower to "process", makes you stuck in a UI so you're vulnerable, etc..)

**Comment by ShimmyMySherbet** [comment]
Feature is going into the backlog for a future release.
Main reasoning is that the primary interface for commands is the ship Terminal, and it tries in well with game play.
This issue will be re-opened when reviewed.
